<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5rFpKnz' shared service.

return $this->privates['.service_locator.5rFpKnz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\GamereqsController::delete' => ['privates', '.service_locator.AhiQxOe', 'get_ServiceLocator_AhiQxOeService.php', true],
    'App\\Controller\\GamereqsController::edit' => ['privates', '.service_locator.AhiQxOe', 'get_ServiceLocator_AhiQxOeService.php', true],
    'App\\Controller\\GamereqsController::show' => ['privates', '.service_locator.AhiQxOe', 'get_ServiceLocator_AhiQxOeService.php', true],
    'App\\Controller\\GamesController::delete' => ['privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true],
    'App\\Controller\\GamesController::edit' => ['privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true],
    'App\\Controller\\GamesController::games' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\GamesController::show' => ['privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\GamereqsController:delete' => ['privates', '.service_locator.AhiQxOe', 'get_ServiceLocator_AhiQxOeService.php', true],
    'App\\Controller\\GamereqsController:edit' => ['privates', '.service_locator.AhiQxOe', 'get_ServiceLocator_AhiQxOeService.php', true],
    'App\\Controller\\GamereqsController:show' => ['privates', '.service_locator.AhiQxOe', 'get_ServiceLocator_AhiQxOeService.php', true],
    'App\\Controller\\GamesController:delete' => ['privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true],
    'App\\Controller\\GamesController:edit' => ['privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true],
    'App\\Controller\\GamesController:games' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\GamesController:show' => ['privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\GamereqsController::delete' => '?',
    'App\\Controller\\GamereqsController::edit' => '?',
    'App\\Controller\\GamereqsController::show' => '?',
    'App\\Controller\\GamesController::delete' => '?',
    'App\\Controller\\GamesController::edit' => '?',
    'App\\Controller\\GamesController::games' => '?',
    'App\\Controller\\GamesController::show' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\GamereqsController:delete' => '?',
    'App\\Controller\\GamereqsController:edit' => '?',
    'App\\Controller\\GamereqsController:show' => '?',
    'App\\Controller\\GamesController:delete' => '?',
    'App\\Controller\\GamesController:edit' => '?',
    'App\\Controller\\GamesController:games' => '?',
    'App\\Controller\\GamesController:show' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
