<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFC72LPE\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFC72LPE/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFC72LPE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFC72LPE\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerFC72LPE\srcApp_KernelProdContainer([
    'container.build_hash' => 'FC72LPE',
    'container.build_id' => '8d17cd79',
    'container.build_time' => 1573430980,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFC72LPE');
