<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'gamereqs_index' => [[], ['_controller' => 'App\\Controller\\GamereqsController::index'], [], [['text', '/gamereqs/']], [], []],
    'gamereqs_new' => [[], ['_controller' => 'App\\Controller\\GamereqsController::new'], [], [['text', '/gamereqs/new']], [], []],
    'gamereqs_show' => [['gamerid'], ['_controller' => 'App\\Controller\\GamereqsController::show'], [], [['variable', '/', '[^/]++', 'gamerid', true], ['text', '/gamereqs']], [], []],
    'gamereqs_edit' => [['gamerid'], ['_controller' => 'App\\Controller\\GamereqsController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'gamerid', true], ['text', '/gamereqs']], [], []],
    'gamereqs_delete' => [['gamerid'], ['_controller' => 'App\\Controller\\GamereqsController::delete'], [], [['variable', '/', '[^/]++', 'gamerid', true], ['text', '/gamereqs']], [], []],
    'games_index' => [[], ['_controller' => 'App\\Controller\\GamesController::index'], [], [['text', '/games/']], [], []],
    'games_new' => [[], ['_controller' => 'App\\Controller\\GamesController::new'], [], [['text', '/games/new']], [], []],
    'games_show' => [['gameid'], ['_controller' => 'App\\Controller\\GamesController::show'], [], [['variable', '/', '[^/]++', 'gameid', true], ['text', '/games']], [], []],
    'games_edit' => [['gameid'], ['_controller' => 'App\\Controller\\GamesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'gameid', true], ['text', '/games']], [], []],
    'games_delete' => [['gameid'], ['_controller' => 'App\\Controller\\GamesController::delete'], [], [['variable', '/', '[^/]++', 'gameid', true], ['text', '/games']], [], []],
    'login_fail' => [[], ['_controller' => 'App\\Controller\\LoginFailController::index'], [], [['text', '/login/fail']], [], []],
    'login_success' => [[], ['_controller' => 'App\\Controller\\LoginSuccessController::index'], [], [['text', '/login/success']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'homepage' => [[], ['_controller' => 'AppBundle:Home:index'], [], [['text', '/login']], [], []],
];
