<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AhiQxOe' shared service.

return $this->privates['.service_locator.AhiQxOe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'gamereq' => ['privates', '.errored..service_locator.AhiQxOe.App\\Entity\\Gamereqs', NULL, 'Cannot autowire service ".service_locator.AhiQxOe": it references class "App\\Entity\\Gamereqs" but no such service exists.'],
], [
    'gamereq' => 'App\\Entity\\Gamereqs',
]);
