<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'gamereqs_index' => [[], ['_controller' => 'App\\Controller\\GamereqsController::index'], [], [['text', '/gamereqs/']], [], []],
    'gamereqs_new' => [[], ['_controller' => 'App\\Controller\\GamereqsController::new'], [], [['text', '/gamereqs/new']], [], []],
    'gamereqs_show' => [['gamerid'], ['_controller' => 'App\\Controller\\GamereqsController::show'], [], [['variable', '/', '[^/]++', 'gamerid', true], ['text', '/gamereqs']], [], []],
    'gamereqs_edit' => [['gamerid'], ['_controller' => 'App\\Controller\\GamereqsController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'gamerid', true], ['text', '/gamereqs']], [], []],
    'gamereqs_delete' => [['gamerid'], ['_controller' => 'App\\Controller\\GamereqsController::delete'], [], [['variable', '/', '[^/]++', 'gamerid', true], ['text', '/gamereqs']], [], []],
    'games_index' => [[], ['_controller' => 'App\\Controller\\GamesController::index'], [], [['text', '/games/']], [], []],
    'games_new' => [[], ['_controller' => 'App\\Controller\\GamesController::new'], [], [['text', '/games/new']], [], []],
    'games_show' => [['gameid'], ['_controller' => 'App\\Controller\\GamesController::show'], [], [['variable', '/', '[^/]++', 'gameid', true], ['text', '/games']], [], []],
    'games_edit' => [['gameid'], ['_controller' => 'App\\Controller\\GamesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'gameid', true], ['text', '/games']], [], []],
    'games_delete' => [['gameid'], ['_controller' => 'App\\Controller\\GamesController::delete'], [], [['variable', '/', '[^/]++', 'gameid', true], ['text', '/games']], [], []],
    'login_fail' => [[], ['_controller' => 'App\\Controller\\LoginFailController::index'], [], [['text', '/login/fail']], [], []],
    'login_success' => [[], ['_controller' => 'App\\Controller\\LoginSuccessController::index'], [], [['text', '/login/success']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'homepage' => [[], ['_controller' => 'AppBundle:Home:index'], [], [['text', '/login']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/']], [], []],
];
