<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Submissions extends \App\Entity\Submissions implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'subid', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'completehrs', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'speedrunhrs', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'mainhrs', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'gameid', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'userid'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'subid', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'completehrs', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'speedrunhrs', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'mainhrs', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'gameid', '' . "\0" . 'App\\Entity\\Submissions' . "\0" . 'userid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Submissions $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSubid(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSubid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubid', []);

        return parent::getSubid();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompletehrs(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompletehrs', []);

        return parent::getCompletehrs();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompletehrs(?int $completehrs): \App\Entity\Submissions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompletehrs', [$completehrs]);

        return parent::setCompletehrs($completehrs);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeedrunhrs(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeedrunhrs', []);

        return parent::getSpeedrunhrs();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeedrunhrs(?int $speedrunhrs): \App\Entity\Submissions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeedrunhrs', [$speedrunhrs]);

        return parent::setSpeedrunhrs($speedrunhrs);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainhrs(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainhrs', []);

        return parent::getMainhrs();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainhrs(?int $mainhrs): \App\Entity\Submissions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainhrs', [$mainhrs]);

        return parent::setMainhrs($mainhrs);
    }

    /**
     * {@inheritDoc}
     */
    public function getGameid(): ?\App\Entity\Games
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGameid', []);

        return parent::getGameid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGameid(?\App\Entity\Games $gameid): \App\Entity\Submissions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGameid', [$gameid]);

        return parent::setGameid($gameid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', []);

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid(?\App\Entity\Users $userid): \App\Entity\Submissions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', [$userid]);

        return parent::setUserid($userid);
    }

}
